Feature/public profil
WildCodeSchool/tlse-php-202109-p2-meetzic pull request #6
Opened 2021-10-30 07:57 UTC by Barthel31

2021-10-30 18:48 UTC, Julien-Savean commented on src/View/PublicProfil/_form.html.twig
> +<label for="avatar">Votre photo :
Ajouter une indentation ?

2021-10-30 19:55 UTC, Barthel31 commented
C'est juste un premier jet avec les inputs...j'ai pas réussi à faire appel
à la base de donnée même avec workbench.
Je retente lundi pour voir si je peux , mais il me semble que je n'arrive
pas à m'y connecter,

Le sam. 30 oct. 2021 à 20:49, Julien Savéan ***@***.***> a
écrit :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/View/PublicProfil/_form.html.twig
> <https://github.com/WildCodeSchool/tlse-php-202109-p2-meetzic/pull/6#discussion_r739686219>
> :
>
> > @@ -0,0 +1,36 @@
> +<form action="" method="get" class="formulaire">
> +<label for="avatar">Votre photo :
>
> Ajouter une indentation ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WildCodeSchool/tlse-php-202109-p2-meetzic/pull/6#pullrequestreview-793596429>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARP3WVDEJ343HUHSJ34PZQDUJRD3BANCNFSM5HAZFQEQ>
> .
>

2021-11-01 12:42 UTC, Julien-Savean commented on src/View/PublicProfil/_form.html.twig
> +<label for="avatar">Votre photo :
ok

2021-11-01 15:15 UTC, bastienwcs requested changes

2021-11-01 15:15 UTC, bastienwcs commented on src/Controller/HomeController.php
> +    public function publicProfil()
Un saut de ligne à ajouter avant la fonction

2021-11-01 15:15 UTC, bastienwcs commented on src/View/PublicProfil/_form.html.twig
> +            <option value="begginer">Débutant</option>
beginner

2021-11-01 15:15 UTC, bastienwcs commented on src/View/PublicProfil/_form.html.twig
> +    <label for="groupe">
band

2021-11-01 15:15 UTC, bastienwcs commented on src/View/PublicProfil/publicProfil.html.twig
> +{% extends 'layout.html.twig' %}
dossier et fichier : publicProfile (avec un e)

2021-11-01 15:15 UTC, bastienwcs commented on src/routes.php
> +    'profil' => ['HomeController', 'publicProfil'],
l'URL peut rester profil (en français) mais le fichier doit être en anglais (profile)

2021-11-02 14:43 UTC, bastienwcs approved these changes

2021-11-02 15:23 UTC, merged